#!/usr/bin/env bash
# configuring web-02 to be identical to web-01.
# then adding  custom Nginx response header
# the goal is to know which server had answered your
# HTTPS requests
# $hostname header to know which server with X-Served-By

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart 
