#!/usr/bin/env bash
# This invoilves configuring HAproxy on your lb-01 server

sudo apt-get -y update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update

sudo apt-get install -y haproxy=2.8.

server_config=\
"
frontend http-frontend
        bind *:80
        mode http
        default_backend http-backend

backend http-backend
        balance roundrobin
        server 337188-web-01 52.3.251.10 check
        server 337188-web-02 52.3.220.106 check
"
echo "$server_config" |sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
