#!/usr/bin/env bash
# bash script which displays content of file
#/etc/passwd.



while read -r line; do
  echo "$line" | cut -d ':' -f1,3,6 #colon delimeter
done < "/etc/passwd" # read fields 1,2,3 input from file<
