#!/usr/bin/env bash
# a bash script which displays one to twenty but 4
# 9 and 17 have bad luck china, japan and italy respectively


counter=1

while [ $counter -le 20 ]
do
	echo $counter
	case $counter in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)

 			;;
	esac # end of case block
	counter=$((counter + 1))
done
